name: master deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  build-and-deploy:
    permissions:
      contents: write
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: build
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
